---
abstract: 'Dummy dist to test PAUSE indexing'
author:
  - '梁宇明 <yuming888@yahoo.co.id>'
build_requires:
  Module::Build: 0.3601
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200007, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: LYUMING-Dummy-Dist3
requires:
  List::Util: 0
  Test::More: 0.96
  perl: 5.010000
resources:
  homepage: http://search.cpan.org/dist/LYUMING-Dummy-Dist3/
version: 0.02
